language: rust
sudo: false
addons:
  apt:
    packages:
      - liblzma5

notifications:
  irc:
    nick: xz-rs
    channels:
      - irc.uriirc.org:16667#hyeon
    template:
      - "#%{build_number} %{result}, %{build_url}"
    skip_join: true
