sudo: false
language: rust

cache:
  directories:
    - ~/.cargo
    - target

notifications:
  irc:
    nick: xz-rs
    channels: 'ircs://irc.uriirc.org:16664#hyeon'
    template: '#%{build_number} %{result}, %{build_url}'
    skip_join: true
