[package]
name = "perf-probe"
version = "0.1.0"
edition = "2024"
publish = false

[features]
default = []
xz-core = ["dep:xz-core"]
xz-core-custom-allocator = ["xz-core", "xz-core/custom_allocator"]
xz-sys = ["dep:xz-sys"]
liblzma-sys = ["dep:liblzma-sys"]

[dependencies]
libc = "0.2"
liblzma-sys = { version = "0.4.6", optional = true }
xz-core = { path = "../xz-core", optional = true }
xz-sys = { path = "../xz-sys", optional = true }
